-- Auto-generated export SQL from current Supabase project
-- Generated by scripts/export_supabase_to_sql.mjs

begin;

-- tour_content_items: skipped (table not found in current project)

-- tour_page_covers: skipped (table not found in current project)

-- feedback (7 rows)
insert into public."feedback" ("id", "created_at", "title", "feedback_date", "description", "country", "name", "profile_pic_url")
values
(1, '2026-04-01T09:00:07.835832+00:00', 'Cultural Heritage Tour', '2026-04-22', 'Our guide made the experience unforgettable. The attention to detail and local knowledge was impressive. Best tour I''ve ever taken!', 'United States', 'Scarlett', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775049489818-nzcws1a33pg.jpeg'),
(2, '2026-04-01T13:27:40.067044+00:00', 'Ella Tour', '2025-07-15', 'Professional and punctual. The safari he organized was the highlight of our tour.', 'USA', 'Noah Johnson', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775050058443-dwuhqf0jh6e.jpeg'),
(3, '2026-04-01T13:31:09.326083+00:00', 'Yala National Park', '2025-06-09', 'Highly recommend! He tailored the itinerary perfectly to fit our interests.', 'USA', 'Isabella Garcia', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775050267701-gcoch6ti69q.jpeg'),
(4, '2026-04-01T13:34:15.04103+00:00', 'Splendor Tour', '2026-04-01', 'The best way to see the island. Great vehicle and even better company!', 'Australia', 'Amelia Brown', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775050452876-tafjxb8pme.jpeg'),
(5, '2026-04-01T13:36:33.433025+00:00', 'Nights Classic Escape', '2025-11-18', 'Best guide in Sri Lanka! He showed us hidden gems we never would have found.', 'Australia', 'Jack Wilson', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775050591647-uk5wfn7q3dp.jpeg'),
(6, '2026-04-01T13:54:59.940858+00:00', 'Nature & Safari Tour', '2024-12-18', 'Excellent service! A very safe driver and highly knowledgeable about history.', 'Germany', 'Henry Müller', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775051697888-hqj99a2jjwb.jpeg'),
(7, '2026-04-01T13:57:13.28657+00:00', 'Supreme Sri Lanka Tour', '2023-08-23', 'Amazing local insights. He is very patient and knows the best food spots!', 'Italy', 'Luca Rossi', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/feedback_client_pic/feedback/1775051831165-riyedx1zyda.jpeg');

-- contact (2 rows)
insert into public."contact" ("id", "created_at", "name", "email", "phone_number", "travel_date", "head_count", "trip_details")
values
(1, '2026-04-01T07:06:03.923608+00:00', 'K Gavindu Ushan', 'rathnayakagavindu98@gmail.com', '0712256555', '2026-01-14T00:00:00+00:00', 2, 'description'),
(2, '2026-04-28T05:21:31.83002+00:00', 'K Gavindu Ushan', 'rathnayakagavindu98@gmail.com', '+94712256555', '2026-04-30T00:00:00+00:00', 7, 'test');

-- tour_memories (55 rows)
insert into public."tour_memories" ("id", "created_at", "title", "description", "traveler_count", "place", "date", "url")
values
(35, '2026-04-27T16:23:01.765628+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306979233-s6xnfwhrwf.jpeg'),
(4, '2026-04-01T11:46:50.52578+00:00', 'Tour with two persons', 'Test description', '2', 'Ella', '2025-12-19T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775044149921-c5ouonnc706.jpeg'),
(5, '2026-04-01T12:04:58.020471+00:00', 'sample text', 'sample text', '5', 'sample text', '2026-03-10T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045094681-woqswvcq2of.jpeg'),
(8, '2026-04-01T12:07:03.7924+00:00', 'sample text', 'sample text
', '6', 'sample text', '2026-01-15T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045221403-2kbizjcousm.jpeg'),
(9, '2026-04-01T12:07:32.074852+00:00', 'sample text', 'sample text
', '6', 'sample text', '2026-02-19T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045250019-mwd9wcg5kqm.jpeg'),
(10, '2026-04-01T12:07:57.832255+00:00', 'sample text', 'sample text
', '4', 'sample text', '2026-03-21T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045275851-l974jjajtf.jpeg'),
(11, '2026-04-01T12:08:34.587559+00:00', 'sample text', 'sample text
', '7', 'sample text', '2026-02-21T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045312481-svcg19ye7y.jpeg'),
(12, '2026-04-01T12:08:56.588052+00:00', 'sample text', 'sample text
', '4', 'sample text', '2026-02-14T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045333424-z30hws2y1vh.jpeg'),
(13, '2026-04-01T12:09:36.884153+00:00', 'sample text', 'sample text', '4', 'sample text', '2025-12-13T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045374299-cedm61y1gb8.jpeg'),
(14, '2026-04-01T12:10:09.07121+00:00', 'sample text', 'sample text', '5', 'sample text', '2025-09-12T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045406842-3ef0vw0sem4.jpeg'),
(15, '2026-04-01T12:10:32.851921+00:00', 'sample text', 'sample text', '8', 'sample text', '2025-10-02T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045430956-3afe6dqzlrc.jpeg'),
(16, '2026-04-01T12:11:11.627002+00:00', 'sample text', 'sample text', '9', 'sample text', '2025-07-18T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045468971-4u150sw7kct.jpeg'),
(17, '2026-04-01T12:11:34.734608+00:00', 'sample text', 'sample text', '8', 'sample text', '2025-09-19T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045492793-xsscrmbkqg.jpeg'),
(18, '2026-04-01T12:11:59.022821+00:00', 'sample text', 'sample text', '4', 'sample text', '2025-02-14T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045517221-4w7wkn5110v.jpeg'),
(19, '2026-04-01T12:12:30.493293+00:00', 'sample text', 'sample text', '4', 'sample text', '2025-09-13T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045548117-ryrc837fzhc.jpeg'),
(20, '2026-04-01T12:12:56.686919+00:00', 'sample text', 'sample text', '5', 'sample text', '2025-07-11T00:00:00+00:00', 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1775045574888-9ievn9k61qe.jpeg'),
(21, '2026-04-27T16:18:46.815926+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306723229-bxhx5jsf997.jpeg'),
(22, '2026-04-27T16:19:16.986+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306754231-6035tcutfc.jpeg'),
(23, '2026-04-27T16:19:40.094154+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306777876-l142vmeed6.jpeg'),
(24, '2026-04-27T16:19:56.438995+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306794386-0yttnkofrfkk.jpeg'),
(25, '2026-04-27T16:20:12.829465+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306810256-3vlorn6jx9x.jpeg'),
(26, '2026-04-27T16:20:30.777072+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306828431-z25ux0w2uw.jpeg'),
(27, '2026-04-27T16:20:44.664702+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306843074-tw062hfm59g.jpeg'),
(28, '2026-04-27T16:21:09.970984+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306867474-oo7gmbcei1.jpeg'),
(29, '2026-04-27T16:21:32.004579+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306890315-9t13vtclep6.jpeg'),
(30, '2026-04-27T16:21:53.255056+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306910378-61jq59gebf3.jpeg'),
(31, '2026-04-27T16:22:06.489746+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306924600-hif3ptz17x6.jpeg'),
(32, '2026-04-27T16:22:20.132173+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306937909-y424tg2acsq.jpeg'),
(33, '2026-04-27T16:22:34.393162+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306952328-3qtzlsn0s4e.jpeg'),
(34, '2026-04-27T16:22:48.2166+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306966844-qbcaf587vxj.jpeg'),
(36, '2026-04-27T16:23:17.013604+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777306994904-ikk08n7xbz.jpeg'),
(37, '2026-04-27T16:23:35.92154+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307014014-l1ephum1egq.jpeg'),
(38, '2026-04-27T16:23:48.995837+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307026670-ruy0efzuwiq.jpeg'),
(39, '2026-04-27T16:24:10.726303+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307048631-7ksaf2prhsb.jpeg'),
(40, '2026-04-27T16:24:25.746012+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307063003-ttafaennd3d.jpeg'),
(41, '2026-04-27T16:24:40.061084+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307078237-z6b37x9c3uf.jpeg'),
(42, '2026-04-27T16:24:53.297504+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307091840-nfdlan8q27.jpeg'),
(43, '2026-04-27T16:25:06.625068+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307104845-0dps4f1icxyd.jpeg'),
(44, '2026-04-27T16:25:19.680863+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307116640-qvrx8v61uub.jpeg'),
(45, '2026-04-27T16:25:34.057302+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307131472-uukug0zbzr.jpeg'),
(46, '2026-04-27T16:25:55.250768+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307152651-2ksax4zspmq.jpeg'),
(47, '2026-04-27T16:26:08.409231+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307166613-veohd4isydo.jpeg'),
(48, '2026-04-27T16:26:29.318147+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307187387-hn97ic1u38i.jpeg'),
(49, '2026-04-27T16:26:55.309045+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307213411-rr4rxw4hhaj.jpeg'),
(50, '2026-04-27T16:27:09.085396+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307226568-jasku6e95uc.jpeg'),
(52, '2026-04-27T16:27:35.868862+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307254347-1hn0bi6z7jvi.jpeg'),
(55, '2026-04-27T16:28:24.807452+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307302977-6gtvnwe8leh.jpeg'),
(58, '2026-04-27T16:29:02.160556+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307339701-5qtl6bgfg6q.jpeg'),
(51, '2026-04-27T16:27:22.614689+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307240577-2kcpgvfoiq9.jpeg'),
(53, '2026-04-27T16:27:54.378038+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307272574-p4sew08ft0q.jpeg'),
(54, '2026-04-27T16:28:12.187179+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307290337-89aenooayr4.jpeg'),
(56, '2026-04-27T16:28:35.656402+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307314152-n2onrxn89b.jpeg'),
(57, '2026-04-27T16:28:48.103552+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307326314-rxg0ckibu8j.jpeg'),
(59, '2026-04-27T16:29:16.134642+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307353867-m8a5vsk4x8n.jpeg'),
(60, '2026-04-27T16:29:29.230915+00:00', '', '', '', '', NULL, 'https://pqqitxvcovnzyltzwavl.supabase.co/storage/v1/object/public/tour_memories/memories/1777307367364-uvfb34yzyu.jpeg');

commit;
